import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const credentialStyles = readFileSync(new URL('./CredentialSections.module.scss', import.meta.url), 'utf8')
const themeStyles = readFileSync(new URL('../../../styles/themes.scss', import.meta.url), 'utf8')
const credentialShellSource = readFileSync(new URL('./CredentialSectionShell.tsx', import.meta.url), 'utf8')
const credentialHealthSource = readFileSync(new URL('./CredentialHealthPanel.tsx', import.meta.url), 'utf8')
const aiProviderSectionSource = readFileSync(new URL('./AiProviderCredentialsSection.tsx', import.meta.url), 'utf8')
const authFileSectionSource = readFileSync(new URL('./AuthFileCredentialsSection.tsx', import.meta.url), 'utf8')

const cssBlock = (selector: string) => {
  const start = credentialStyles.indexOf(selector)
  expect(start).toBeGreaterThanOrEqual(0)
  const next = credentialStyles.indexOf('\n.', start + selector.length)
  return credentialStyles.slice(start, next === -1 ? undefined : next)
}

describe('Credential section styles', () => {
  it('keeps Auth Files and AI Provider row sizing separate', () => {
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?grid-template-columns:\s*200px minmax\(0, 448px\) minmax\(250px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?\.credentialIdentityBlock\s*\{[\s\S]*?max-width:\s*200px;/)
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?@include tablet\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?@include mobile\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?grid-template-columns:\s*200px minmax\(0, 448px\) minmax\(250px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?\.credentialIdentityBlock\s*\{[\s\S]*?max-width:\s*200px;/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?@include tablet\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?@include mobile\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialShellSource).toContain('rowClassName?: string')
    expect(aiProviderSectionSource).toContain('rowClassName={styles.aiProviderCredentialRow}')
    expect(authFileSectionSource).toContain('rowClassName={styles.authFileCredentialRow}')
    expect(authFileSectionSource).toContain('<AuthFileDisplayModeSwitch')
    expect(authFileSectionSource).toContain('readStoredAuthFileDisplayMode')
    expect(authFileSectionSource).toContain('persistAuthFileDisplayMode(mode)')
    expect(authFileSectionSource).toContain("mode === 'quota'")
    expect(authFileSectionSource).toContain("displayMode === 'health'")
    expect(authFileSectionSource).not.toContain('mockCredentialsMode')
    expect(authFileSectionSource).not.toContain('isMockCredentialsMode')
    expect(authFileSectionSource).toContain('CredentialHealthPanel')
    expect(authFileSectionSource).toContain('lastUsedAt={row.identity.last_used_at}')
    expect(authFileSectionSource).toContain('statsUpdatedAt={row.identity.stats_updated_at}')
    expect(aiProviderSectionSource).toContain('CredentialHealthPanel')
    expect(aiProviderSectionSource).toContain('lastUsedAt={row.lastUsedText}')
    expect(aiProviderSectionSource).toContain('statsUpdatedAt={row.statsUpdatedText}')
    expect(aiProviderSectionSource).not.toContain('DisplayModeSwitch')
    expect(authFileSectionSource).not.toContain('aiProviderCredentialRow')
  })

  it('lets Auth Files quota bars wrap before their blocks overlap', () => {
    expect(credentialStyles).toMatch(/\.credentialRow\s*\{[\s\S]*?column-gap:\s*18px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(350px, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?gap:\s*14px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(150px, 1fr\)\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBars\s*\{[\s\S]*?gap:\s*14px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBarBlock\s*\{[\s\S]*?min-width:\s*150px;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayModeSwitcher\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/)
    expect(credentialStyles).toMatch(/\.credentialDisplayModeSwitcher\s*\{[\s\S]*?min-width:\s*162px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthGrid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(30, 4px\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthGrid\s*\{[\s\S]*?gap:\s*3px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?width:\s*4px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?box-shadow:\s*none;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellSuccess\s*\{[\s\S]*?height:\s*22px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellSuccess\s*\{[\s\S]*?background:\s*#22c55e;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellWarning\s*\{[\s\S]*?height:\s*16px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellWarning\s*\{[\s\S]*?background:\s*#facc15;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellFailure\s*\{[\s\S]*?height:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellFailure\s*\{[\s\S]*?background:\s*#ef4444;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellEmpty\s*\{[\s\S]*?height:\s*5px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellEmpty\s*\{[\s\S]*?background:\s*#e5e7eb;/)
    expect(cssBlock('.credentialHealthCellSuccess')).not.toContain('linear-gradient')
    expect(cssBlock('.credentialHealthCellWarning')).not.toContain('linear-gradient')
    expect(cssBlock('.credentialHealthCellFailure')).not.toContain('linear-gradient')
    expect(credentialStyles).not.toContain('credentialQuotaChips')
    expect(credentialStyles).not.toContain('credentialQuotaChip')
    expect(credentialStyles).not.toContain('credentialQuotaSidePanel')
    expect(credentialStyles).not.toContain('credentialQuotaRow')
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?grid-template-columns:\s*max-content minmax\(160px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?column-gap:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthChart\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMeta\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMeta\s*\{[\s\S]*?gap:\s*7px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimes\s*\{[\s\S]*?display:\s*flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimes\s*\{[\s\S]*?gap:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTime\s*\{[\s\S]*?display:\s*inline-flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimeIcon\s*\{[\s\S]*?width:\s*11px;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialHealthPanel\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
    expect(credentialHealthSource).toContain('credentialHealthChart')
    expect(credentialHealthSource).toContain('credentialHealthMeta')
    expect(credentialHealthSource).toContain('IconTimer')
    expect(credentialHealthSource).toContain('IconRefreshCw')
  })

  it('uses a nested Auth Files active-only switch that matches the project pill controls', () => {
    expect(authFileSectionSource).toContain('credentialActiveOnlyLabel')
    expect(authFileSectionSource).toContain('credentialActiveOnlyTrack')
    expect(authFileSectionSource).toContain('credentialActiveOnlyThumb')
    expect(authFileSectionSource).toMatch(/credentialActiveOnlyLabel[\s\S]*?credentials_auth_files_active_only[\s\S]*?type="checkbox"[\s\S]*?credentialActiveOnlyTrack/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?min-height:\s*34px;/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?padding:\s*4px 5px 4px 10px;/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?border:\s*1px solid var\(--border-color\);/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?background:\s*color-mix\(in srgb, var\(--bg-secondary\) 78%, transparent\);/)
    expect(cssBlock('.credentialActiveOnlySwitch')).toContain('color: var(--text-primary);')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('color: #2d2a26;')
    expect(themeStyles).toMatch(/:root\s*\{[\s\S]*?--text-primary:\s*#2d2a26;/)
    expect(themeStyles).toMatch(/\[data-theme='white'\]\s*\{[\s\S]*?--text-primary:\s*#2d2a26;/)
    expect(cssBlock('.credentialActiveOnlySwitch')).toContain('font-size: 11px;')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('font-size: 12px;')
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?box-shadow:\s*inset 0 1px 0 rgba\(255, 255, 255, 0\.06\);/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlyThumb\s*\{[\s\S]*?background:\s*linear-gradient\(145deg, #fff, color-mix\(in srgb, var\(--bg-primary\) 86%, #dbeafe\)\);/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack\s*\{[\s\S]*?#2563eb/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack\s*\{[\s\S]*?#38bdf8/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack\s*\{[\s\S]*?#67e8f9/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack \.credentialActiveOnlyThumb\s*\{[\s\S]*?transform:\s*translateX\(18px\);/)
    expect(cssBlock('.credentialActiveOnlyTrack')).not.toContain('backdrop-filter')
    expect(cssBlock('.credentialActiveOnlyTrack')).not.toContain('box-shadow')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toMatch(/&:hover\s+\.credentialActiveOnlyTrack/)
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('#34c759')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('var(--primary-color)')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('var(--accent-color)')
    expect(credentialStyles).not.toContain('#34c759')
  })

  it('renders Auth Files health buckets as compact hover detail targets', () => {
    expect(credentialHealthSource).toContain('usage_stats.credentials_health_grid_aria')
    expect(credentialHealthSource).toContain('usage_stats.credentials_health_bucket_aria')
    expect(credentialHealthSource).toContain('bucket.successCount')
    expect(credentialHealthSource).toContain('bucket.failureCount')
    expect(credentialHealthSource).toContain('credentialHealthTooltip')
    expect(credentialHealthSource).toMatch(/<span[\s\S]*?role="listitem"[\s\S]*?className=\{`\$\{styles\.credentialHealthCell/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?position:\s*relative;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?border:\s*0;/)
    expect(cssBlock('.credentialHealthCell')).toContain('cursor: help;')
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?transition:\s*transform 0\.16s ease/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?border-radius:\s*3px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell:hover[\s\S]*?transform:\s*translateY\(-2px\) scale\(1\.2\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?position:\s*absolute;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?font-size:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?font-weight:\s*400;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?opacity:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell:hover \.credentialHealthTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).not.toMatch(/\.credentialHealthCell:focus-visible/)
    expect(credentialHealthSource).not.toMatch(/<button[\s\S]*?credentialHealthCell/)
  })

  it('keeps shared credential table headers out of narrow row stacking', () => {
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialTableHeader\.authFileCredentialRow[\s\S]*?display:\s*none;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialTableHeader\.aiProviderCredentialRow[\s\S]*?display:\s*none;/)
  })

  it('stacks Auth Files quota error status above the message', () => {
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorSummary\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorSummary\s*\{[\s\S]*?align-items:\s*flex-start;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorMessage\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorMessage\s*\{[\s\S]*?line-height:\s*1\.35;/)
  })

  it('keeps Auth Files quota actions inside the mobile card boundary', () => {
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaBarBlock\s*\{[\s\S]*?min-width:\s*0;/)
  })

  it('renders compact priority badges without lengthening credential names', () => {
    expect(credentialStyles).toMatch(/\.credentialPriorityBadge\s*\{[\s\S]*?min-width:\s*22px;/)
    expect(credentialShellSource).toContain('CredentialPriorityBadge')
    expect(authFileSectionSource).toContain('row.priorityLabel')
    expect(authFileSectionSource).toMatch(/row\.planTypeLabel[\s\S]*?row\.remainingDaysLabel[\s\S]*?row\.priorityLabel/)
    expect(aiProviderSectionSource).toContain('row.priorityLabel')
  })

  it('keeps Auth Files inspection separate from the quota refresh pill', () => {
    expect(authFileSectionSource).toContain('credentialSectionActionButtons')
    expect(authFileSectionSource).toMatch(/credentialInspectionSwitcher[\s\S]*?credentialInspectionButton[\s\S]*?credentialRefreshSwitcher/)
    expect(authFileSectionSource).toContain('credentialInspectionButton')
    expect(authFileSectionSource).toMatch(/credentialInspectionButton[\s\S]*?credentialRefreshSwitcher/)
    expect(authFileSectionSource).toMatch(/credentialRefreshSwitcher\} \$\{styles\.credentialInspectionSwitcher[\s\S]*?credentialInspectionButton[\s\S]*?<\/div>\s*<div className=\{styles\.credentialRefreshSwitcher\}>[\s\S]*?credentialRefreshButtonLoading/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSwitcher\s*\{[\s\S]*?border-radius:\s*999px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSwitcher\s*\{[\s\S]*?background:\s*color-mix\(in srgb, var\(--bg-secondary\) 78%, transparent\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressTrack\s*\{[\s\S]*?height:\s*8px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressTrack\s*\{[\s\S]*?background:\s*var\(--bg-tertiary\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressTrack\s*\{[\s\S]*?border:\s*1px solid var\(--border-color\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressFill\s*\{[^}]*background:\s*linear-gradient\(90deg, #15803d, #22c55e\);/)
    expect(credentialStyles).not.toMatch(/\.credentialInspectionProgressFill\s*\{[^}]*box-shadow:/)
    expect(credentialStyles).not.toContain('.credentialInspectionProgressFill::after')
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 80px\) minmax\(260px, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?align-items:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?gap:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?padding-bottom:\s*34px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionMetric\s*\{[\s\S]*?align-self:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionMetric\s*\{[\s\S]*?align-content:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionStartButton\s*\{[\s\S]*?align-self:\s*center;/)
    expect(cssBlock('.credentialInspectionStatCardUnauthorized')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialInspectionStatCardLimitReached')).toContain('color: var(--quota-medium-color);')
    expect(cssBlock('.credentialInspectionStatusUnauthorized')).toContain('background: color-mix(in srgb, var(--danger-color) 12%, transparent);')
    expect(cssBlock('.credentialInspectionStatusUnauthorized')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialInspectionStatusLimitReached')).toContain('background: color-mix(in srgb, var(--quota-medium-color) 16%, transparent);')
    expect(cssBlock('.credentialInspectionStatusLimitReached')).toContain('color: var(--quota-medium-color);')
    expect(authFileSectionSource).toContain('status?.completed_at')
    expect(authFileSectionSource).toContain('credentials_inspection_limit_reached')
    expect(authFileSectionSource).toContain('credentials_inspection_401_402')
    expect(authFileSectionSource).toContain('credentials_inspection_unknown')
    expect(authFileSectionSource).not.toContain('<small>{result.auth_index}</small>')
    expect(authFileSectionSource).toContain('result.name || result.file_name')
    expect(credentialStyles).toMatch(/\.credentialInspectionStatsGrid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\);/)
    expect(cssBlock('.credentialInspectionStatCardUnknown')).toContain('color: var(--text-secondary);')
    expect(credentialStyles).not.toContain('.credentialInspectionStatCardPayment')
    expect(authFileSectionSource).toContain('role="progressbar"')
    expect(authFileSectionSource).toContain('aria-valuenow={progress}')
    expect(authFileSectionSource).toContain('aria-valuemin={0}')
    expect(authFileSectionSource).toContain('aria-valuemax={100}')
    expect(authFileSectionSource).toContain('buildInspectionResultsPage')
    expect(authFileSectionSource).toContain('nextInspectionResultStatusFilter')
    expect(authFileSectionSource).toContain('INSPECTION_RESULT_PAGE_SIZE_OPTIONS')
    expect(authFileSectionSource).toContain('credentialInspectionStatButton')
    expect(authFileSectionSource).toContain('credentialInspectionResultsFooter')
    expect(authFileSectionSource).not.toContain('results.slice(0, 8)')
    expect(authFileSectionSource).not.toContain('status?.payment_required_402 ?? 0')
    expect(authFileSectionSource).not.toContain('filterStatus="payment_required_402"')
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsTable\s*\{[\s\S]*?max-height:\s*min\(52vh, 520px\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsTable\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsFooter\s*\{[\s\S]*?justify-content:\s*flex-end;/)
  })


  it('stacks Auth Files quota reset and refresh actions on the right side', () => {
    expect(authFileSectionSource).toContain('credentialQuotaActionStack')
    expect(authFileSectionSource).toContain('credentialRowResetButton')
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(350px, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaActionStack\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaActionStack\s*\{[\s\S]*?justify-content:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialRowResetButton\s*\{[\s\S]*?background:\s*var\(--bg-secondary\);/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?align-items:\s*center;/)
  })

  it('keeps Auth Files quota reset popovers visible outside the section card', () => {
    expect(authFileSectionSource).toContain('credentialQuotaResetPopover')
    expect(credentialStyles).toMatch(/\.credentialSectionCard\s*\{[\s\S]*?overflow:\s*hidden;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetAction\s*\{[\s\S]*?position:\s*relative;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?position:\s*fixed;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTooltip\s*\{[\s\S]*?position:\s*absolute;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTooltip\s*\{[\s\S]*?right:\s*calc\(100% \+ 8px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetAction:hover \.credentialQuotaResetTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).not.toContain('.credentialQuotaResetAction:focus-within .credentialQuotaResetTooltip')
    expect(credentialStyles).toMatch(/\.credentialQuotaResetCount\s*\{[\s\S]*?color:\s*var\(--primary-active\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetCount\s*\{[\s\S]*?font-weight:\s*700;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?background:\s*var\(--primary-color\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?color:\s*var\(--primary-contrast, #fff\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?&:hover:not\(:disabled\)\s*\{[\s\S]*?background:\s*var\(--primary-hover\);/)
    expect(cssBlock('.credentialSectionCard')).not.toContain('overflow: visible;')
  })

  it('places the Auth Files quota usage mode switch in the pagination toolbar before sorting', () => {
    expect(authFileSectionSource).toContain('credentialQuotaActionStack')
    expect(credentialStyles).toContain('credentialQuotaActionStack')
    expect(authFileSectionSource).toContain('leadingControls={showHealthMode ? undefined : <QuotaUsageModeSwitch')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_label')
    expect(authFileSectionSource).toContain('credentialQuotaModeSwitcher')
    expect(credentialShellSource).toMatch(/\{leadingControls\}[\s\S]*?\{sortOptions/)
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_current')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_estimated')
    expect(credentialStyles).toMatch(/\.credentialQuotaModeControl\s*\{[\s\S]*?display:\s*flex;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaModeSwitcher\s*\{[\s\S]*?border-radius:\s*999px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaModeThumbEstimated\s*\{[\s\S]*?transform:\s*translateX\(100%\);/)
    expect(credentialHealthSource).toContain('HEALTH_BUCKET_MINUTES = 10')
    expect(credentialHealthSource).toContain('HEALTH_BUCKET_COUNT = HEALTH_WINDOW_MINUTES / HEALTH_BUCKET_MINUTES')
  })

  it('renders credential metrics under a shared table header instead of repeating row labels', () => {
    expect(credentialShellSource).toContain('CredentialTableHeader')
    expect(authFileSectionSource).toContain('<CredentialTableHeader')
    expect(aiProviderSectionSource).toContain('<CredentialTableHeader')
    expect(authFileSectionSource).toContain("nameLabel={t('usage_stats.credentials_column_name')}")
    expect(authFileSectionSource).toContain("sideLabel={showHealthMode ? t('usage_stats.credentials_column_health') : t('usage_stats.credentials_column_quota')}")
    expect(aiProviderSectionSource).toContain("sideLabel={t('usage_stats.credentials_column_health')}")
    expect(credentialStyles).toMatch(/\.credentialTableHeader\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialTableHeader\s*\{[\s\S]*?column-gap:\s*18px;/)
    expect(credentialStyles).toMatch(/\.credentialMetricHeaderGroup[\s\S]*?\.credentialMetricGroup\s*\{[\s\S]*?grid-template-columns:\s*minmax\(136px, 1\.45fr\) minmax\(88px, 0\.9fr\) minmax\(92px, 0\.9fr\) minmax\(84px, 0\.8fr\);/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?overflow-wrap:\s*anywhere;/)
    expect(credentialStyles).toMatch(/\.credentialMetricHeaderCell\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).not.toContain('grid-template-columns: var(--credential-request-metric-width')
    expect(credentialShellSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(credentialShellSource).not.toContain('--credential-request-metric-width')
    expect(authFileSectionSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(aiProviderSectionSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(credentialShellSource).not.toContain('credentialMetricLabel')
    expect(credentialStyles).toMatch(/\.credentialMetricValueCell\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?align-items:\s*baseline;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?flex-wrap:\s*wrap;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?display:\s*inline-flex;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?line-height:\s*1\.2;/)
  })

  it('uses a fixed centered pagination bar height', () => {
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?--usage-pagination-bar-height:\s*51px;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?height:\s*var\(--usage-pagination-bar-height\);/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?box-sizing:\s*border-box;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?align-items:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?padding:\s*0 22px;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialPagination\s*\{[\s\S]*?overflow-x:\s*auto;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialPaginationControls\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialQuotaModeControl[\s\S]*?\.credentialPageSizeControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialPagination\s*\{[\s\S]*?overflow-x:\s*auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialPaginationControls\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaModeControl[\s\S]*?\.credentialPageSizeControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialPageSizeControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
  })

  it('keeps plan and remaining-day badges readable in dark mode', () => {
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialPlanBadgeTeam[\s\S]*?color:\s*#bbf7d0;/)
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialPlanBadgePlus[\s\S]*?color:\s*#bfdbfe;/)
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialPlanBadgePro[\s\S]*?color:\s*#fde68a;/)
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialRemainingDaysBadge[\s\S]*?color:\s*#bbf7d0;/)
  })
})
