import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const credentialStyles = readFileSync(new URL('../CredentialSections.module.scss', import.meta.url), 'utf8')
const themeStyles = readFileSync(new URL('../../../../styles/themes.scss', import.meta.url), 'utf8')
const credentialShellSource = readFileSync(new URL('../CredentialSectionShell.tsx', import.meta.url), 'utf8')
const credentialHealthSource = readFileSync(new URL('../CredentialHealthPanel.tsx', import.meta.url), 'utf8')
const aiProviderSectionSource = readFileSync(new URL('../AiProviderCredentialsSection.tsx', import.meta.url), 'utf8')
const authFileSectionSource = readFileSync(new URL('../AuthFileCredentialsSection.tsx', import.meta.url), 'utf8')
const providerFilterSource = readFileSync(new URL('../CredentialProviderFilterBar.tsx', import.meta.url), 'utf8')

const cssBlock = (selector: string) => {
  const start = credentialStyles.indexOf(selector)
  expect(start).toBeGreaterThanOrEqual(0)
  const next = credentialStyles.indexOf('\n.', start + selector.length)
  return credentialStyles.slice(start, next === -1 ? undefined : next)
}

const scssRule = (source: string, selector: string, occurrence = 0) => {
  let start = -selector.length
  for (let index = 0; index <= occurrence; index += 1) {
    start = source.indexOf(selector, start + selector.length)
    expect(start).toBeGreaterThanOrEqual(0)
  }

  const openingBrace = source.indexOf('{', start + selector.length)
  expect(openingBrace).toBeGreaterThan(start)
  let depth = 1
  for (let index = openingBrace + 1; index < source.length; index += 1) {
    if (source[index] === '{') {
      depth += 1
    } else if (source[index] === '}' && --depth === 0) {
      return source.slice(start, index + 1)
    }
  }
  throw new Error(`Unclosed SCSS rule: ${selector}`)
}

describe('Credential section styles', () => {
  it('uses the global card contract and a stable credential title track', () => {
    expect(credentialShellSource).toMatch(/className=\{`\$\{styles\.credentialSectionCard\} keeper-card-surface`\}/)
    expect(credentialShellSource).toMatch(/className=\{`\$\{styles\.credentialSectionTitleRow\} keeper-card-title-track`\}/)
    expect(credentialShellSource).toMatch(/className=\{`\$\{styles\.credentialSectionTitle\} keeper-card-title`\}/)
    expect(credentialShellSource).toMatch(/className=\{`\$\{styles\.credentialSectionSubtitle\} keeper-card-subtitle`\}/)

    expect(credentialStyles).toMatch(/\.credentialSectionHeader\s*\{[\s\S]*?display:\s*grid;[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/\.credentialSectionActions\s*\{[\s\S]*?min-height:\s*var\(--keeper-card-title-track-height\);[\s\S]*?align-items:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialSectionTitleRow\s*\{[\s\S]*?flex-wrap:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialSectionTitleBlock\s*\{[\s\S]*?min-width:\s*0;/)
    expect(cssBlock('.credentialSectionTitleBlock')).not.toContain('display: contents;')
    expect(credentialStyles).toMatch(/\.credentialSectionTitleRow\s*\{[\s\S]*?min-height:\s*34px;/)
    expect(credentialStyles).toMatch(/\.credentialSectionActions\s*\{[\s\S]*?align-self:\s*flex-end;/)
    expect(credentialStyles).toMatch(/\.credentialSectionSubtitle\s*\{[\s\S]*?font-size:\s*var\(--keeper-card-subtitle-size\);[\s\S]*?font-weight:\s*var\(--keeper-card-subtitle-weight\);/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);[\s\S]*?\.credentialSectionTitleRow\s*\{[\s\S]*?flex-wrap:\s*wrap;/)

    const cardBlock = cssBlock('.credentialSectionCard')
    expect(cardBlock).not.toContain('border: 1px solid')
    expect(cardBlock).not.toContain('border-radius: 24px')
    expect(cardBlock).not.toContain('box-shadow:')
    expect(authFileSectionSource.match(/<MainActionButton/g)).toHaveLength(2)
    expect(authFileSectionSource).toContain("import { MainActionButton } from '@/components/ui/MainActionButton'")
    expect(credentialStyles).not.toContain('.credentialRefreshButton')
  })

  it('keeps Auth Files and AI Provider row sizing separate', () => {
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?grid-template-columns:\s*\$credential-name-column-width minmax\(0, 448px\) minmax\(250px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?\.credentialIdentityBlock\s*\{[\s\S]*?max-width:\s*\$credential-name-column-width;/)
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?@include tablet\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialStyles).toMatch(/\.authFileCredentialRow\s*\{[\s\S]*?@include mobile\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?grid-template-columns:\s*\$credential-name-column-width minmax\(0, 448px\) minmax\(250px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?\.credentialIdentityBlock\s*\{[\s\S]*?max-width:\s*\$credential-name-column-width;/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?@include tablet\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialStyles).toMatch(/\.aiProviderCredentialRow\s*\{[\s\S]*?@include mobile\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(credentialShellSource).toContain('rowClassName?: string')
    expect(aiProviderSectionSource).toContain('rowClassName={styles.aiProviderCredentialRow}')
    expect(authFileSectionSource).toContain('rowClassName={styles.authFileCredentialRow}')
    expect(authFileSectionSource).toContain('<AuthFileDisplayModeSwitch')
    expect(authFileSectionSource).toContain('readStoredAuthFileDisplayMode')
    expect(authFileSectionSource).toContain('persistAuthFileDisplayMode(mode)')
    expect(authFileSectionSource).toContain("mode === 'quota'")
    expect(authFileSectionSource).toContain("displayMode === 'health'")
    expect(authFileSectionSource).not.toContain('mockCredentialsMode')
    expect(authFileSectionSource).not.toContain('isMockCredentialsMode')
    expect(authFileSectionSource).toContain('CredentialHealthPanel')
    expect(authFileSectionSource).toContain('lastUsedAt={row.identity.last_used_at}')
    expect(authFileSectionSource).toContain('statsUpdatedAt={row.identity.stats_updated_at}')
    expect(authFileSectionSource).toContain('windowCacheReadRate={row.windowCacheReadRate}')
    expect(aiProviderSectionSource).toContain('CredentialHealthPanel')
    expect(aiProviderSectionSource).toContain('lastUsedAt={row.lastUsedText}')
    expect(aiProviderSectionSource).toContain('statsUpdatedAt={row.statsUpdatedText}')
    expect(aiProviderSectionSource).not.toContain('DisplayModeSwitch')
    expect(authFileSectionSource).not.toContain('aiProviderCredentialRow')
  })

  it('reveals a reserved detail arrow without underlining or repainting credential names', () => {
    const detailNameButton = scssRule(credentialStyles, '.credentialDetailNameButton')
    const detailNameText = scssRule(credentialStyles, '.credentialDetailNameText', 2)
    const detailNameArrow = scssRule(credentialStyles, '.credentialDetailNameArrow', 2)
    const authFileArrowSlot = scssRule(credentialStyles, '.authFileCredentialRow .credentialDetailNameArrow')
    const authFileRowHover = scssRule(credentialStyles, '.authFileCredentialRow:hover')
    const arrowMotion = scssRule(credentialStyles, '@keyframes credentialDetailArrowNudge')
    const reducedMotion = scssRule(credentialStyles, '@media (prefers-reduced-motion: reduce)')
    expect(detailNameButton).toContain('&:hover')
    expect(detailNameButton).toContain('color: var(--primary-color)')
    expect(detailNameButton).toContain('.credentialDetailNameText')
    expect(detailNameButton).toContain('transform: translateY(-1px)')
    expect(detailNameButton).toContain('.credentialDetailNameArrow')
    expect(detailNameButton).toContain('min-width: 0')
    expect(detailNameButton).not.toContain('background: color-mix')
    expect(detailNameButton).not.toContain('text-decoration: underline')
    expect(detailNameText).toContain('display: inline-block')
    expect(detailNameText).toContain('min-width: 0')
    expect(detailNameText).toContain('overflow-wrap: anywhere')
    expect(detailNameText).toContain('transform: translateY(0)')
    expect(detailNameText).toContain('transition: transform 0.16s ease-out')
    expect(detailNameArrow).toContain('flex: 0 0 10px')
    expect(detailNameArrow).toContain('opacity: 0')
    expect(detailNameArrow).toContain('transform: translateX(-2px)')
    expect(detailNameArrow).toContain('transition: opacity 0.16s ease-out, transform 0.16s ease-out')
    expect(authFileArrowSlot).toContain('margin-right: 4px')
    expect(authFileRowHover).toContain('.credentialDetailNameArrow')
    expect(authFileRowHover).toContain('opacity: 1')
    expect(authFileRowHover).toContain('animation: credentialDetailArrowNudge 0.72s ease-in-out infinite alternate')
    expect(arrowMotion).toContain('transform: translateX(0)')
    expect(arrowMotion).toContain('transform: translateX(4px)')
    expect(reducedMotion).toContain('.credentialDetailNameText')
    expect(reducedMotion).toContain('.authFileCredentialRow:hover .credentialDetailNameArrow')
    expect(reducedMotion).toContain('animation: none')
  })

  it('passes explicit shared logo sizes and accessible row labels to every context', () => {
    const filterIconFrameStyles = cssBlock('.credentialProviderFilterIconFrame')
    const identityBlockStyles = cssBlock('.credentialIdentityBlock')
    const identityContentStyles = cssBlock('.credentialIdentityContent')

    expect(credentialStyles).toMatch(/\$credential-provider-icon-size:\s*30px;/)
    expect(filterIconFrameStyles).toContain('width: $credential-provider-icon-size;')
    expect(filterIconFrameStyles).toContain('height: $credential-provider-icon-size;')
    expect(filterIconFrameStyles).not.toContain('border:')
    expect(filterIconFrameStyles).not.toContain('border-radius:')
    expect(filterIconFrameStyles).not.toContain('background:')
    expect(filterIconFrameStyles).not.toContain('overflow: hidden;')
    expect(filterIconFrameStyles).toMatch(/> svg\s*\{[\s\S]*?width:\s*100%;[\s\S]*?height:\s*100%;/)
    expect(providerFilterSource).toMatch(/<ProviderBrandIcon providerType=\{option\.knownKey \?\? option\.key\} size="100%" \/>/)
    expect(authFileSectionSource).toMatch(/<ProviderBrandIcon providerType=\{row\.identity\.type\} size=\{30\} ariaLabel=\{row\.typeLabel\} \/>/)
    expect(aiProviderSectionSource).toMatch(/<ProviderBrandIcon providerType=\{row\.identity\.type\} size=\{30\} ariaLabel=\{row\.typeLabel\} \/>/)
    expect(authFileSectionSource).toMatch(/<ProviderBrandIcon providerType=\{result\.type\} size=\{20\} \/>/)
    expect(identityBlockStyles).toContain('display: flex;')
    expect(identityBlockStyles).toContain('align-items: center;')
    expect(identityBlockStyles).toContain('gap: $credential-provider-icon-gap;')
    expect(identityContentStyles).toContain('min-height: 40px;')
    expect(credentialStyles).not.toMatch(/\.credentialProviderFilterIcon\s*\{/)
    expect(credentialStyles).not.toMatch(/\.credentialNameProviderIcon\s*\{/)
    expect(credentialStyles).not.toMatch(/\.credentialInspectionProviderIcon\s*\{/)
    expect(credentialShellSource).toMatch(/credentialIdentityBlock[\s\S]*?\{icon\}[\s\S]*?credentialIdentityContent[\s\S]*?credentialNameRow[\s\S]*?credentialIdentityText/)
  })

  it('preserves the pre-logo credential name content width', () => {
    expect(credentialStyles).toMatch(/\$credential-name-content-width:\s*236px;/)
    expect(credentialStyles).toMatch(/\$credential-provider-icon-gap:\s*14px;/)
    expect(credentialStyles).toMatch(/\$credential-name-column-width:\s*\$credential-name-content-width \+ \$credential-provider-icon-size \+ \$credential-provider-icon-gap;/)
  })

  it('lets Auth Files quota bars wrap before their blocks overlap', () => {
    expect(credentialStyles).toMatch(/\.credentialRow\s*\{[\s\S]*?column-gap:\s*18px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(350px, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?gap:\s*14px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(150px, 1fr\)\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBars\s*\{[\s\S]*?gap:\s*14px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBarBlock\s*\{[\s\S]*?min-width:\s*150px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupLabel\s*\{[\s\S]*?color:\s*var\(--text-tertiary\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltip\s*\{[\s\S]*?opacity:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget\s*\{[\s\S]*?cursor:\s*default;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltip\s*\{[\s\S]*?max-width:\s*min\(240px, 70vw\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltip\s*\{[\s\S]*?overflow-wrap:\s*anywhere;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget \.credentialQuotaGroupTooltip\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget:hover \.credentialQuotaGroupTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget:focus-visible \.credentialQuotaGroupTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBarBlock:nth-child\(even\) \.credentialQuotaGroupTooltip\s*\{[\s\S]*?right:\s*0;[\s\S]*?left:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBarBlock:nth-child\(even\) \.credentialQuotaGroupTooltip::after\s*\{[\s\S]*?right:\s*14px;[\s\S]*?left:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTime\s*\{[\s\S]*?margin-left:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayModeSwitcher\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/)
    expect(credentialStyles).toMatch(/\.credentialDisplayModeSwitcher\s*\{[\s\S]*?min-width:\s*162px;/)
    expect(cssBlock('.credentialHealthGrid')).toContain('grid-template-columns: repeat(30, 4px);')
    expect(cssBlock('.credentialHealthGrid')).toContain('gap: 4px;')
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?width:\s*4px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?box-shadow:\s*none;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?cursor:\s*default;/)
    expect(cssBlock('.credentialHealthCell')).not.toContain('cursor: help;')
    expect(credentialStyles).toMatch(/\.credentialHealthCellSuccess\s*\{[\s\S]*?background:\s*#22c55e;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellWarning\s*\{[\s\S]*?background:\s*#facc15;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellFailure\s*\{[\s\S]*?background:\s*#ef4444;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellEmpty\s*\{[\s\S]*?background:\s*#e5e7eb;/)
    expect(cssBlock('.credentialHealthCellSuccess')).not.toContain('height:')
    expect(cssBlock('.credentialHealthCellWarning')).not.toContain('height:')
    expect(cssBlock('.credentialHealthCellFailure')).not.toContain('height:')
    expect(cssBlock('.credentialHealthCellEmpty')).not.toContain('height:')
    expect(credentialHealthSource).toContain('style={{ height: `${bucket.heightPx}px` }}')
    expect(cssBlock('.credentialHealthMetaUnhealthy .credentialHealthMetaStatus')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialHealthCellSuccess')).not.toContain('linear-gradient')
    expect(cssBlock('.credentialHealthCellWarning')).not.toContain('linear-gradient')
    expect(cssBlock('.credentialHealthCellFailure')).not.toContain('linear-gradient')
    expect(credentialStyles).not.toContain('credentialQuotaChips')
    expect(credentialStyles).not.toContain('credentialQuotaChip')
    expect(credentialStyles).not.toContain('credentialQuotaSidePanel')
    expect(credentialStyles).not.toContain('credentialQuotaRow')
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?grid-template-columns:\s*max-content minmax\(160px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?column-gap:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthChart\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMeta\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMeta\s*\{[\s\S]*?gap:\s*7px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimes\s*\{[\s\S]*?display:\s*flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimes\s*\{[\s\S]*?gap:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTime\s*\{[\s\S]*?display:\s*inline-flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimeIcon\s*\{[\s\S]*?width:\s*11px;/)
    // 5h 缓存率复用 meta 区一行文字，不再引入第二条柱状图或额外序列色。
    expect(credentialStyles).toMatch(/\.credentialHealthMetaCache\s*\{[\s\S]*?display:\s*flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaCacheValue\s*\{[\s\S]*?font-variant-numeric:\s*tabular-nums;/)
    expect(cssBlock('.credentialHealthMetaCacheLabel')).toContain('color: var(--text-tertiary);')
    expect(credentialHealthSource).toContain('credentials_health_cache_rate_5h')
    expect(credentialHealthSource).toContain('cacheReadRateTone')
    expect(credentialHealthSource).not.toContain('credentialHealthCacheGrid')
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialHealthPanel\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
    expect(credentialHealthSource).toContain('credentialHealthChart')
    expect(credentialHealthSource).toContain('credentialHealthMeta')
    expect(credentialHealthSource).toContain('IconTimer')
    expect(credentialHealthSource).toContain('IconRefreshCw')
  })

  it('uses a nested Auth Files active-only switch that matches the project pill controls', () => {
    expect(authFileSectionSource).toContain('credentialActiveOnlyLabel')
    expect(authFileSectionSource).toContain('credentialActiveOnlyTrack')
    expect(authFileSectionSource).toContain('credentialActiveOnlyThumb')
    expect(authFileSectionSource).toMatch(/credentialActiveOnlyLabel[\s\S]*?credentials_auth_files_active_only[\s\S]*?type="checkbox"[\s\S]*?credentialActiveOnlyTrack/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?min-height:\s*34px;/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?padding:\s*4px 5px 4px 10px;/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?border:\s*1px solid var\(--border-color\);/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?background:\s*color-mix\(in srgb, var\(--bg-secondary\) 78%, transparent\);/)
    expect(cssBlock('.credentialActiveOnlySwitch')).toContain('color: var(--text-primary);')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('color: #2d2a26;')
    expect(themeStyles).toMatch(/:root\s*\{[\s\S]*?--text-primary:\s*#2d2a26;/)
    expect(themeStyles).toMatch(/\[data-theme='white'\]\s*\{[\s\S]*?--text-primary:\s*#2d2a26;/)
    expect(cssBlock('.credentialActiveOnlySwitch')).toContain('font-size: 11px;')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('font-size: 12px;')
    expect(credentialStyles).toMatch(/\.credentialActiveOnlySwitch\s*\{[\s\S]*?box-shadow:\s*inset 0 1px 0 rgba\(255, 255, 255, 0\.06\);/)
    expect(credentialStyles).toMatch(/\.credentialActiveOnlyThumb\s*\{[\s\S]*?background:\s*linear-gradient\(145deg, #fff, color-mix\(in srgb, var\(--bg-primary\) 86%, #dbeafe\)\);/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack\s*\{[\s\S]*?#2563eb/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack\s*\{[\s\S]*?#38bdf8/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack\s*\{[\s\S]*?#67e8f9/)
    expect(credentialStyles).toMatch(/input:checked \+ \.credentialActiveOnlyTrack \.credentialActiveOnlyThumb\s*\{[\s\S]*?transform:\s*translateX\(18px\);/)
    expect(cssBlock('.credentialActiveOnlyTrack')).not.toContain('backdrop-filter')
    expect(cssBlock('.credentialActiveOnlyTrack')).not.toContain('box-shadow')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toMatch(/&:hover\s+\.credentialActiveOnlyTrack/)
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('#34c759')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('var(--primary-color)')
    expect(cssBlock('.credentialActiveOnlySwitch')).not.toContain('var(--accent-color)')
    expect(credentialStyles).not.toContain('#34c759')
  })

  it('keeps scheduled refresh controls stable, clear, and compact', () => {
    const scheduleGridStyles = cssBlock('.credentialAutoRefreshScheduleGrid')
    const unitSwitcherStyles = cssBlock('.credentialAutoRefreshUnitSwitcher')
    const intervalFieldStyles = cssBlock('.credentialAutoRefreshIntervalField')
    const intervalControlStyles = scssRule(intervalFieldStyles, 'input,')
    const tipStyles = cssBlock('.credentialAutoRefreshScheduleTip')

    expect(authFileSectionSource).toContain('credentialAutoRefreshScheduleArea')
    expect(authFileSectionSource).toContain('credentialAutoRefreshScheduleAreaActive')
    expect(authFileSectionSource).toContain('credentialAutoRefreshIntervalField')
    expect(authFileSectionSource).toContain('credentialAutoRefreshUnitSuffix')
    expect(authFileSectionSource).not.toContain('credentialAutoRefreshField')
    expect(authFileSectionSource).toContain('width={620}')
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshSettingsModal\s*\{[\s\S]*?max-width:\s*min\(620px, calc\(100vw - 28px\)\);/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshScheduleArea\s*\{[\s\S]*?grid-template-rows:\s*0fr;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshScheduleArea\s*\{[\s\S]*?transition:\s*grid-template-rows 0\.18s ease, opacity 0\.16s ease;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshScheduleAreaActive\s*\{[\s\S]*?grid-template-rows:\s*1fr;/)
    expect(scheduleGridStyles).toContain('grid-template-columns: minmax(300px, 1fr) 256px;')
    expect(scheduleGridStyles).toContain('column-gap: 8px;')
    expect(scheduleGridStyles).toContain('align-items: center;')
    expect(scheduleGridStyles).toContain('overflow: visible;')
    expect(unitSwitcherStyles).toContain('grid-template-columns: repeat(4, minmax(0, 1fr));')
    expect(unitSwitcherStyles).toContain('width: 100%;')
    expect(unitSwitcherStyles).toContain('white-space: nowrap;')
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitButtonActive\s*\{[\s\S]*?background:\s*linear-gradient\(135deg, var\(--primary-color\), var\(--primary-hover\)\) !important;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitButtonActive\s*\{[\s\S]*?color:\s*var\(--primary-contrast, #fff\) !important;/)
    expect(intervalFieldStyles).toContain('grid-template-columns: 64px 100px 68px;')
    expect(intervalFieldStyles).toContain('align-items: center;')
    expect(intervalFieldStyles).toContain('justify-self: end;')
    expect(intervalFieldStyles).toContain('column-gap: 12px;')
    expect(intervalFieldStyles).toContain('width: 256px;')
    expect(intervalFieldStyles).toContain('max-width: 100%;')
    expect(intervalControlStyles).toContain('min-height: 36px;')
    expect(intervalControlStyles).toContain('border-radius: 999px;')
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshIntervalField\s*\{[\s\S]*?input,\s*select\s*\{[\s\S]*?text-align:\s*center;/)
    expect(intervalFieldStyles).toMatch(/select\s*\{[\s\S]*?grid-column:\s*span 2;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshIntervalLabel\s*\{[\s\S]*?text-align:\s*right;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitSuffix\s*\{[\s\S]*?text-align:\s*left;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitSuffix\s*\{[\s\S]*?overflow:\s*visible;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitSuffix\s*\{[\s\S]*?text-overflow:\s*clip;/)
    expect(authFileSectionSource).toContain('credentialAutoRefreshScheduleTip')
    expect(tipStyles).toContain('margin-top: 8px;')
    expect(tipStyles).toContain('font-size: 12px;')
    expect(tipStyles).toContain('line-height: 1.45;')
  })

  it('renders Auth Files health buckets as compact hover detail targets', () => {
    expect(credentialHealthSource).toContain('usage_stats.credentials_health_grid_aria')
    expect(credentialHealthSource).toContain('usage_stats.credentials_health_bucket_aria')
    expect(credentialHealthSource).toContain('bucket.successCount')
    expect(credentialHealthSource).toContain('bucket.failureCount')
    expect(credentialHealthSource).toContain('credentialHealthTooltip')
    expect(credentialHealthSource).toMatch(/<span[\s\S]*?role="listitem"[\s\S]*?className=\{`\$\{styles\.credentialHealthCell/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?position:\s*relative;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?border:\s*0;/)
    expect(cssBlock('.credentialHealthCell')).toContain('cursor: default;')
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?transition:\s*transform 0\.16s ease/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?border-radius:\s*3px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell:hover[\s\S]*?transform:\s*translateY\(-2px\) scale\(1\.2\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?position:\s*absolute;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?font-size:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?font-weight:\s*400;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?opacity:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell:hover \.credentialHealthTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).not.toMatch(/\.credentialHealthCell:focus-visible/)
    expect(credentialHealthSource).not.toMatch(/<button[\s\S]*?credentialHealthCell/)
  })

  it('keeps shared credential table headers out of narrow row stacking', () => {
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialTableHeader\.authFileCredentialRow[\s\S]*?display:\s*none;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialTableHeader\.aiProviderCredentialRow[\s\S]*?display:\s*none;/)
  })

  it('stacks Auth Files quota error status above the message', () => {
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorSummary\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorSummary\s*\{[\s\S]*?align-items:\s*flex-start;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorMessage\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorMessage\s*\{[\s\S]*?line-height:\s*1\.35;/)
  })

  it('keeps Auth Files quota actions inside the mobile card boundary', () => {
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaBarBlock\s*\{[\s\S]*?min-width:\s*0;/)
  })

  it('renders compact priority badges without lengthening credential names', () => {
    expect(credentialStyles).toMatch(/\.credentialPriorityBadge\s*\{[\s\S]*?min-width:\s*22px;/)
    expect(credentialShellSource).toContain('CredentialPriorityBadge')
    expect(authFileSectionSource).toContain('row.priorityLabel')
    expect(authFileSectionSource).toMatch(/row\.subscriptionBadge[\s\S]*?row\.remainingDaysLabel[\s\S]*?row\.priorityLabel/)
    expect(aiProviderSectionSource).toContain('row.priorityLabel')
  })

  it('uses a portal-based floating tooltip for credential expiry badges', () => {
    expect(authFileSectionSource).toContain('createPortal')
    expect(authFileSectionSource).toContain('className={styles.credentialRemainingDaysBadge}')
    expect(authFileSectionSource).toContain('className={styles.credentialExpiryTooltip}')
    expect(authFileSectionSource).toContain('role="tooltip"')
    expect(credentialStyles).toMatch(/\.credentialExpiryTooltip\s*\{[\s\S]*?position:\s*fixed;/)
    expect(credentialStyles).toMatch(/\.credentialExpiryTooltip\s*\{[\s\S]*?z-index:\s*2100;/)
    expect(credentialStyles).toMatch(/\.credentialExpiryTooltip\s*\{[\s\S]*?pointer-events:\s*none;/)
    expect(credentialStyles).toMatch(/\.credentialExpiryTooltip\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(cssBlock('.credentialExpiryTooltip')).not.toContain('overflow-wrap:')
  })

  it('keeps credential alias edit buttons in a fixed name-cell action slot', () => {
    expect(credentialStyles).toMatch(/\.credentialNameMain\s*\{[\s\S]*?display:\s*flex;[\s\S]*?gap:\s*8px;[\s\S]*?width:\s*100%;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?width:\s*100%;/)
    expect(credentialStyles).toMatch(/\.credentialAliasEditor\s*\{[\s\S]*?width:\s*100%;/)
    expect(credentialStyles).toMatch(/\.credentialAliasDisplayLayout\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialAliasDisplayLayout\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 28px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasDisplayLayout\s*\{[\s\S]*?column-gap:\s*8px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasNameSlot\s*\{[\s\S]*?min-width:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialAliasNameSlot\s*\{[\s\S]*?overflow-wrap:\s*anywhere;/)
    expect(credentialStyles).toMatch(/\.credentialAliasActionSlot\s*\{[\s\S]*?width:\s*24px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasActionSlot\s*\{[\s\S]*?justify-self:\s*start;/)
    expect(credentialStyles).not.toMatch(/\.credentialAliasDisplay\s*\{/)
  })

  it('keeps Auth Files inspection separate from the quota refresh pill', () => {
    expect(authFileSectionSource).toContain('credentialSectionActionButtons')
    expect(authFileSectionSource).toMatch(/<MainActionButton[\s\S]*?credentialInspectionButton[\s\S]*?<MainActionButton/)
    expect(authFileSectionSource).toContain('credentialInspectionButton')
    expect(authFileSectionSource).toContain('loading={quotaRefreshing}')
    expect(credentialStyles).not.toContain('.credentialInspectionSwitcher')
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressTrack\s*\{[\s\S]*?height:\s*8px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressTrack\s*\{[\s\S]*?background:\s*var\(--bg-tertiary\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressTrack\s*\{[\s\S]*?border:\s*1px solid var\(--border-color\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionProgressFill\s*\{[^}]*background:\s*linear-gradient\(90deg, #15803d, #22c55e\);/)
    expect(credentialStyles).not.toMatch(/\.credentialInspectionProgressFill\s*\{[^}]*box-shadow:/)
    expect(credentialStyles).not.toContain('.credentialInspectionProgressFill::after')
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 80px\) minmax\(260px, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?align-items:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?gap:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?padding-bottom:\s*34px;/)
    expect(cssBlock('.credentialInspectionStatCard')).toContain('border-radius: var(--keeper-card-radius);')
    expect(credentialStyles).toMatch(/\.credentialInspectionMetric\s*\{[\s\S]*?align-self:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionMetric\s*\{[\s\S]*?align-content:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionStartButton\s*\{[\s\S]*?align-self:\s*center;/)
    expect(cssBlock('.credentialInspectionStatCardUnauthorized')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialInspectionStatCardLimitReached')).toContain('color: var(--quota-medium-color);')
    expect(cssBlock('.credentialInspectionStatusUnauthorized')).toContain('background: color-mix(in srgb, var(--danger-color) 12%, transparent);')
    expect(cssBlock('.credentialInspectionStatusUnauthorized')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialInspectionStatusLimitReached')).toContain('background: color-mix(in srgb, var(--quota-medium-color) 16%, transparent);')
    expect(cssBlock('.credentialInspectionStatusLimitReached')).toContain('color: var(--quota-medium-color);')
    expect(authFileSectionSource).toContain('status?.completed_at')
    expect(authFileSectionSource).toContain('credentials_inspection_limit_reached')
    expect(authFileSectionSource).toContain('credentials_inspection_401_402')
    expect(authFileSectionSource).toContain('credentials_inspection_unknown')
    expect(authFileSectionSource).not.toContain('<small>{result.auth_index}</small>')
    expect(authFileSectionSource).toContain('result.name || result.file_name')
    expect(credentialStyles).toMatch(/\.credentialInspectionStatsGrid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\);/)
    expect(cssBlock('.credentialInspectionStatCardUnknown')).toContain('color: var(--text-secondary);')
    expect(credentialStyles).not.toContain('.credentialInspectionStatCardPayment')
    expect(authFileSectionSource).toContain('role="progressbar"')
    expect(authFileSectionSource).toContain('aria-valuenow={progress}')
    expect(authFileSectionSource).toContain('aria-valuemin={0}')
    expect(authFileSectionSource).toContain('aria-valuemax={100}')
    expect(authFileSectionSource).toContain('buildInspectionResultsPage')
    expect(authFileSectionSource).toContain('nextInspectionResultStatusFilter')
    expect(authFileSectionSource).toContain('INSPECTION_RESULT_PAGE_SIZE_OPTIONS')
    expect(authFileSectionSource).toContain('credentialInspectionStatButton')
    expect(authFileSectionSource).toContain('credentialInspectionResultsFooter')
    expect(authFileSectionSource).not.toContain('results.slice(0, 8)')
    expect(authFileSectionSource).not.toContain('status?.payment_required_402 ?? 0')
    expect(authFileSectionSource).not.toContain('filterStatus="payment_required_402"')
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsTable\s*\{[\s\S]*?max-height:\s*min\(52vh, 520px\);/)
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsTable\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsFooter\s*\{[\s\S]*?justify-content:\s*flex-end;/)
  })


  it('stacks Auth Files quota reset and refresh actions on the right side', () => {
    expect(authFileSectionSource).toContain('credentialQuotaActionStack')
    expect(authFileSectionSource).toContain('credentialRowResetButton')
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(350px, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaActionStack\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaActionStack\s*\{[\s\S]*?justify-content:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialRowResetButton\s*\{[\s\S]*?background:\s*var\(--bg-secondary\);/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?align-items:\s*center;/)
  })

  it('keeps Auth Files quota reset popovers visible outside the section card', () => {
    expect(authFileSectionSource).toContain('credentialQuotaResetPopover')
    expect(credentialStyles).toMatch(/\.credentialSectionCard\s*\{[\s\S]*?overflow:\s*hidden;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetAction\s*\{[\s\S]*?position:\s*relative;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?position:\s*fixed;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?max-height:\s*calc\(100vh - 24px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetExpiryList\s*\{[\s\S]*?max-height:\s*min\(40vh, 220px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetExpiryList\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetActions\s*\{[\s\S]*?flex-shrink:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTooltip\s*\{[\s\S]*?position:\s*absolute;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTooltip\s*\{[\s\S]*?right:\s*calc\(100% \+ 8px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetAction:hover \.credentialQuotaResetTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).not.toContain('.credentialQuotaResetAction:focus-within .credentialQuotaResetTooltip')
    expect(credentialStyles).toMatch(/\.credentialQuotaResetCount\s*\{[\s\S]*?color:\s*var\(--primary-active\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetCount\s*\{[\s\S]*?font-weight:\s*700;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?background:\s*var\(--primary-color\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?color:\s*var\(--primary-contrast, #fff\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?&:hover:not\(:disabled\)\s*\{[\s\S]*?background:\s*var\(--primary-hover\);/)
    expect(cssBlock('.credentialSectionCard')).not.toContain('overflow: visible;')
  })

  it('places the Auth Files quota usage mode switch in the pagination toolbar before sorting', () => {
    const quotaModeControl = scssRule(credentialStyles, '.credentialQuotaModeControl')

    expect(authFileSectionSource).toContain('credentialQuotaActionStack')
    expect(credentialStyles).toContain('credentialQuotaActionStack')
    expect(authFileSectionSource).toContain('leadingControls={showHealthMode ? undefined : <QuotaUsageModeSwitch')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_label')
    expect(authFileSectionSource).toContain('credentialQuotaModeSwitcher')
    expect(credentialShellSource).toMatch(/\{leadingControls\}[\s\S]*?\{sortOptions/)
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_current')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_estimated')
    expect(credentialStyles).toMatch(/\.credentialQuotaModeControl\s*\{[\s\S]*?display:\s*flex;/)
    expect(quotaModeControl).toContain('font-size: 11px')
    expect(credentialStyles).toMatch(/\.credentialQuotaModeSwitcher\s*\{[\s\S]*?border-radius:\s*999px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaModeThumbEstimated\s*\{[\s\S]*?transform:\s*translateX\(100%\);/)
    expect(credentialHealthSource).toContain('HEALTH_BUCKET_MINUTES = 10')
    expect(credentialHealthSource).toContain('HEALTH_BUCKET_COUNT = HEALTH_WINDOW_MINUTES / HEALTH_BUCKET_MINUTES')
  })

  it('renders credential metrics under a shared table header instead of repeating row labels', () => {
    expect(credentialShellSource).toContain('CredentialTableHeader')
    expect(authFileSectionSource).toContain('<CredentialTableHeader')
    expect(aiProviderSectionSource).toContain('<CredentialTableHeader')
    expect(authFileSectionSource).toContain("nameLabel={t('usage_stats.credentials_column_name')}")
    expect(authFileSectionSource).toContain("sideLabel={showHealthMode ? t('usage_stats.credentials_column_health') : t('usage_stats.credentials_column_quota')}")
    expect(aiProviderSectionSource).toContain("sideLabel={t('usage_stats.credentials_column_health')}")
    expect(credentialStyles).toMatch(/\.credentialTableHeader\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialTableHeader\s*\{[\s\S]*?column-gap:\s*18px;/)
    expect(credentialStyles).toMatch(/\.credentialMetricHeaderGroup[\s\S]*?\.credentialMetricGroup\s*\{[\s\S]*?grid-template-columns:\s*minmax\(136px, 1\.45fr\) minmax\(88px, 0\.9fr\) minmax\(92px, 0\.9fr\) minmax\(84px, 0\.8fr\);/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?overflow-wrap:\s*anywhere;/)
    expect(credentialStyles).toMatch(/\.credentialMetricHeaderCell\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).not.toContain('grid-template-columns: var(--credential-request-metric-width')
    expect(credentialShellSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(credentialShellSource).not.toContain('--credential-request-metric-width')
    expect(authFileSectionSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(aiProviderSectionSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(credentialShellSource).not.toContain('credentialMetricLabel')
    expect(credentialStyles).toMatch(/\.credentialMetricValueCell\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?align-items:\s*baseline;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?flex-wrap:\s*wrap;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?display:\s*inline-flex;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?line-height:\s*1\.2;/)
  })

  it('uses a fixed centered pagination bar height', () => {
    const pagination = scssRule(credentialStyles, '.credentialPagination')
    const pageSizeControl = scssRule(credentialStyles, '.credentialPageSizeControl')
    const paginationSelect = scssRule(credentialStyles, '.credentialPaginationSelect')
    const sortControl = scssRule(credentialStyles, '.credentialPaginationSortControl')
    const sortSizer = scssRule(credentialStyles, '.credentialPaginationSortSizer', 1)
    const sortSelect = scssRule(credentialStyles, '.credentialPaginationSortSelect', 1)
    const paginationDropdown = scssRule(credentialStyles, '.credentialPaginationDropdown')

    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?--usage-pagination-bar-height:\s*51px;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?height:\s*var\(--usage-pagination-bar-height\);/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?box-sizing:\s*border-box;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?align-items:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?padding:\s*0 22px;/)
    expect(pagination).toContain('font-size: 11px')
    expect(pageSizeControl).toContain('font-size: 11px')
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialPagination\s*\{[\s\S]*?overflow-x:\s*auto;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialPaginationControls\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/@include tablet\s*\{[\s\S]*?\.credentialQuotaModeControl[\s\S]*?\.credentialPageSizeControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialPagination\s*\{[\s\S]*?overflow-x:\s*auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialPaginationControls\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialQuotaModeControl[\s\S]*?\.credentialPageSizeControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialPageSizeControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
    expect(credentialShellSource).toContain("import { Select } from '@/components/ui/Select'")
    expect(credentialShellSource).not.toContain('<select')
    expect(paginationSelect).toContain(':global(button)')
    expect(paginationSelect).toContain('height: 32px')
    expect(paginationSelect).toContain('border-radius: $radius-full')
    expect(paginationSelect).toContain('background: var(--bg-secondary)')
    expect(credentialShellSource).toContain('data-credential-pagination-sort-sizer="true"')
    expect(credentialShellSource).toContain('sortOptions.map((option) =>')
    expect(sortControl).toContain('display: inline-grid')
    expect(sortSizer).toContain('visibility: hidden')
    expect(sortSizer).toContain('white-space: nowrap')
    expect(sortSizer).toContain('padding: 0 37px 0 10px')
    expect(sortSelect).toContain('width: 100%')
    expect(sortSelect).not.toContain('width: 124px')
    expect(scssRule(credentialStyles, '.credentialPaginationPageSizeSelect')).toContain('width: 64px')
    expect(credentialShellSource.match(/dropdownClassName=\{styles\.credentialPaginationDropdown\}/g)).toHaveLength(2)
    expect(paginationDropdown).toContain(":global([role='option'])")
    expect(paginationDropdown).toContain('font-size: 11px')
  })

  it('gives every Auth Files credential label a dedicated visual treatment', () => {
    const freeRule = scssRule(credentialStyles, '.credentialPlanBadgeFree')
    const plusRule = scssRule(credentialStyles, '.credentialPlanBadgePlus')
    const teamRule = scssRule(credentialStyles, '.credentialPlanBadgeTeam')
    const pro5xRule = scssRule(credentialStyles, '.credentialPlanBadgePro5x')
    const pro20xRule = scssRule(credentialStyles, '.credentialPlanBadgePro20x')
    const enterpriseRule = scssRule(credentialStyles, '.credentialPlanBadgeEnterprise')
    const remainingDaysRule = scssRule(credentialStyles, '.credentialRemainingDaysBadge', 1)
    const priorityRule = scssRule(credentialStyles, '.credentialPriorityBadge')

    expect(freeRule).toContain('#f5eee6')
    expect(freeRule).toMatch(/box-shadow:[\s\S]*?inset 0 1px 0/)
    expect(credentialStyles).not.toContain('.credentialPlanBadgeFree::before')
    expect(plusRule).toContain('#2563eb')
    expect(teamRule).toContain('#16a34a')
    expect(pro5xRule).toContain('--credential-plan-tone-2: #f6dc37')
    expect(pro20xRule).toContain('--credential-plan-tone-2: #f6dc37')
    expect(enterpriseRule).toContain('#c4b5fd')
    expect(credentialStyles).not.toContain('.credentialPlanBadgeClaude')
    expect(credentialStyles).not.toContain('.credentialPlanBadgeAntigravity')
    expect(remainingDaysRule).toContain('radial-gradient')
    expect(priorityRule).toContain('linear-gradient')
  })

  it('preserves every selected Solar Citrine motion layer with compositor-friendly transforms', () => {
    const badgeKeyframes = [...credentialStyles.matchAll(/@keyframes\s+(credentialPlanBadge\w+)/g)].map((match) => match[1])
    expect(badgeKeyframes).toEqual([
      'credentialPlanBadgeSolarFlow',
      'credentialPlanBadgeSolarRotate',
      'credentialPlanBadgeSheen',
    ])
    for (const keyframe of badgeKeyframes) {
      const declarations = [...scssRule(credentialStyles, `@keyframes ${keyframe}`).matchAll(/^\s*([\w-]+)\s*:/gm)].map((match) => match[1])
      expect(new Set(declarations), keyframe).toEqual(new Set(['transform']))
    }
    const badgeAnimationDeclarations = [...credentialStyles.matchAll(/animation:\s*credentialPlanBadge\w+[^;]*;/g)].map((match) => match[0]).sort()
    const sharedMotionRules = [
      scssRule(credentialStyles, '.credentialPlanBadgePlus,'),
      scssRule(credentialStyles, '.credentialPlanBadgeFlow'),
      scssRule(credentialStyles, '.credentialPlanBadgeCorona'),
    ].join('\n')
    const sharedAnimationDeclarations = [...sharedMotionRules.matchAll(/animation:\s*credentialPlanBadge\w+[^;]*;/g)].map((match) => match[0]).sort()
    expect(badgeAnimationDeclarations).toEqual(sharedAnimationDeclarations)
    expect(credentialStyles).not.toContain('@keyframes credentialFreeBadgeRefresh')
    expect(credentialStyles).toContain('@keyframes credentialPlanBadgeSolarFlow')
    expect(credentialStyles).toContain('@keyframes credentialPlanBadgeSolarRotate')
    expect(credentialStyles).toContain('@keyframes credentialPlanBadgeSheen')
    expect(credentialStyles).toMatch(/\.credentialPlanBadgeFlow\s*\{[\s\S]*?repeating-linear-gradient[\s\S]*?animation:\s*credentialPlanBadgeSolarFlow/)
    expect(credentialStyles).toMatch(/\.credentialPlanBadgeCorona\s*\{[\s\S]*?conic-gradient[\s\S]*?animation:\s*credentialPlanBadgeSolarRotate/)
    expect(credentialStyles).toMatch(/repeating-linear-gradient\(116deg,[\s\S]*?68\.30835px\)/)
    expect(credentialStyles).toMatch(/repeating-linear-gradient\(112deg,[\s\S]*?140\.93195px\)/)
    expect(credentialStyles).toMatch(/@keyframes credentialPlanBadgeSolarFlow[\s\S]*?translate3d\(152px, 0, 0\)/)
    expect(credentialStyles).toMatch(/\.credentialPlanBadgePro20x::after\s*\{[\s\S]*?linear-gradient/)
    expect(credentialStyles).toMatch(/\.credentialPlanBadgePro20x\s*\{[\s\S]*?--credential-plan-sheen-duration:\s*4\.8s/)
    expect(credentialStyles).toMatch(/\.credentialPlanBadge\s*\{[\s\S]*?contain:\s*paint;/)
    expect(credentialStyles).not.toContain('background-position:')
    expect(credentialStyles).not.toContain('will-change:')
  })

  it('keeps screen blending by default and disables it only for Safari WebKit', () => {
    const coronaRule = scssRule(credentialStyles, '.credentialPlanBadgeCorona')
    const safariWebKitRule = scssRule(credentialStyles, '@supports (-webkit-nbsp-mode: space)')

    expect(coronaRule).toContain('mix-blend-mode: screen;')
    expect(scssRule(safariWebKitRule, '.credentialPlanBadgeCorona')).toContain('mix-blend-mode: normal;')
    expect(safariWebKitRule).not.toContain('.credentialPlanBadgeFlow')
  })

  it('disables badge motion for reduced-motion and slow-update devices', () => {
    expect(credentialStyles).toMatch(/prefers-reduced-motion:\s*reduce\),\s*\(update:\s*slow\)[\s\S]*?\.credentialPlanBadgeFlow[\s\S]*?\.credentialPlanBadgeCorona[\s\S]*?animation:\s*none/)
    expect(credentialStyles).toMatch(/prefers-reduced-motion:\s*reduce\),\s*\(update:\s*slow\)[\s\S]*?\.credentialPlanBadgeEnterprise::before[\s\S]*?animation:\s*none/)
    expect(credentialStyles).not.toMatch(/prefers-reduced-motion:[\s\S]*?\.credentialPlanBadgeFree::before/)
  })

  it('keeps plan and remaining-day badges readable in dark mode', () => {
    const darkRules = scssRule(credentialStyles, ":global([data-theme='dark'])")
    const darkFreeRule = scssRule(darkRules, '.credentialPlanBadgeFree')

    expect(darkFreeRule).toContain('linear-gradient(145deg, #5b453a')
    expect(darkFreeRule).toContain('color: #f5eee6;')
    expect(scssRule(darkRules, '.credentialPlanBadgeTeam')).toContain('color: #edfff7;')
    expect(scssRule(darkRules, '.credentialPlanBadgePlus')).toContain('color: #edf8ff;')
    expect(scssRule(darkRules, '.credentialPlanBadgePro5x')).toContain('color: #302200;')
    expect(scssRule(darkRules, '.credentialPlanBadgePro20x')).toContain('color: #302200;')
    expect(scssRule(darkRules, '.credentialPlanBadgeEnterprise')).toContain('color: #26324a;')
    expect(scssRule(darkRules, '.credentialRemainingDaysBadge')).toContain('color: #bbf7d0;')
  })
})
